### ISSUE TITLE
ModuleNotFoundError when installing sfmono-square

### ISSUE THREAD

**Issue by acevif** [delphinus/homebrew-sfmono-square#112]
I'm encountering a ModuleNotFoundError when attempting to install sfmono-square 3.2.3.
The error message is as follows:

```
ModuleNotFoundError: No module named 'fontTools'
```

This is the environment:
```
$ python --version
Python 3.12.1
$ sw_vers
ProductName:		macOS
ProductVersion:		14.4
BuildVersion:		23E214
$ brew list --version | rg fonttools
fonttools 4.49.0
```

Any assistance in resolving this issue would be greatly appreciated.
Thank you.

追伸:
すみません、気づかず英訳してissueを立ててしまいました。日本語でも英語でも大丈夫です。

**Comment by delphinus** [comment]
再現しました。修正します。

**Comment by delphinus** [comment]
修正しました。リリースしたらクローズします。

**Comment by acevif** [comment]
@delphinus ありがとうございます!
先ほど試したところ無事インストールできました。

**Comment by delphinus** [comment]
v3.2.4 としてリリースしました。CI で Ventura での実行結果がどうやっても失敗する（フォントは生成されているのに）ので、一時的にオフにしています。また後で考えます。

**Comment by acevif** [comment]
@delphinus ありがとうございます！

**Comment by Zabriskije** [comment]
Getting the same error on macOS 15.0.1 (24A348).


```
==> Installing sfmono-square from delphinus/sfmono-square
==> /usr/bin/xar -xf SF Mono Fonts.pkg
==> /bin/bash -c cat SFMonoFonts.pkg/Payload | gunzip -dc | cpio -i
==> /opt/homebrew/opt/python@3.12/bin/python3.12 -c import sys
sys.path.append('/private/tmp/sfmono-square-20241015-99004-m1oyq5/homebrew-sfmono-square-3.2.6/src')
sys.path.appen
Last 15 lines from /Users/Mac/Library/Logs/Homebrew/sfmono-square/03.python3.12:
-c
import sys
sys.path.append('/private/tmp/sfmono-square-20241015-99004-m1oyq5/homebrew-sfmono-square-3.2.6/src')
sys.path.append('/opt/homebrew/opt/fontforge/libexec/lib/python3.12/site-packages')
sys.path.append('/opt/homebrew/opt/fonttools/libexec/lib/python3.12/site-packages')
import build
sys.exit(build.build('3.2.6'))

Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/private/tmp/sfmono-square-20241015-99004-m1oyq5/homebrew-sfmono-square-3.2.6/src/build.py", line 9, in <module>
    import fonttools
  File "/private/tmp/sfmono-square-20241015-99004-m1oyq5/homebrew-sfmono-square-3.2.6/src/fonttools.py", line 2, in <module>
    from fontTools.ttLib import TTFont
ModuleNotFoundError: No module named 'fontTools'
```

**Comment by delphinus** [comment]
Now fontforge needs **python@3.12* and fonttools needs **python@3.13**…… Hmm, I cannot fix this until upstream fixes.

I'm thinking to remove code depending on fonttools. 🤔

**Comment by delphinus** [comment]
I did PR for this.

https://github.com/Homebrew/homebrew-core/pull/194578

**Comment by delphinus** [comment]
fontforge has been released. I released v3.2.7 to use this. Check it.

**Comment by Zabriskije** [comment]
Solved. Thanks!
