### ISSUE TITLE
build error on Homebrew 4.4.1-41-gad9ea1c

### ISSUE THREAD

**Issue by michael-kallweitt** [delphinus/homebrew-sfmono-square#121]
```
==> /usr/local/opt/python@3.13/bin/python3.13 -c import sys
sys.path.append('/private/tmp/sfmono-square-20241017-27284-v383v8/homebr
Last 15 lines from /Users/administrator/Library/Logs/Homebrew/sfmono-square/03.python3.13:
import sys
sys.path.append('/private/tmp/sfmono-square-20241017-27284-v383v8/homebrew-sfmono-square-3.2.7/src')
sys.path.append('/usr/local/opt/fontforge/libexec/lib/python3.13/site-packages')
sys.path.append('/usr/local/opt/fonttools/libexec/lib/python3.13/site-packages')
import build
sys.exit(build.build('3.2.7'))

Traceback (most recent call last):
  File "<string>", line 5, in <module>
    import build
  File "/private/tmp/sfmono-square-20241017-27284-v383v8/homebrew-sfmono-square-3.2.7/src/build.py", line 9, in <module>
    import fonttools
  File "/private/tmp/sfmono-square-20241017-27284-v383v8/homebrew-sfmono-square-3.2.7/src/fonttools.py", line 2, in <module>
    from fontTools.ttLib import TTFont
ModuleNotFoundError: No module named 'fontTools'
```
Let me add that fonttools (4.54.1) is installed through Homebrew.

**Comment by michael-kallweitt** [comment]
ls: cannot access '/usr/local/opt/fonttools/libexec/lib/python3.13/site-packages': No such file or directory

**Comment by delphinus** [comment]
Then, what do you see with this?

```
ls /usr/local/opt/Cellar/fonttools/4.54.1/libexec/lib/python3.13/site-packages
```

If you see some entries, it seems that fonttools has not been linked.

**Comment by michael-kallweitt** [comment]
ls: cannot access '/usr/local/Cellar/fonttools/4.54.1/libexec/lib/python3.13/site-packages': No such file or directory

`ls -l /usr/local/Cellar/fonttools/4.54.1/libexec/lib/`
```
total 0
drwxr-xr-x 3 administrator 96 Sep 24 16:16 python3.12
```

So, for some reason, there is only a python3.12 directory. :(

**Comment by delphinus** [comment]
I see. Your fonttools was old and used Python 3.12 instead of 3.13. `brew upgrade fonttools` also have solved the issue, maybe.

It seems to be difficult to force using the latest fonttools by this font's formula. So I will close this issue. Feel free to reopen if you have another problem.
